/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'om.sao@oracle.com' at '4/23/18 7:18 PM' with Gradle 2.13
 *
 * @author om.sao@oracle.com, @date '7/17/18 7:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
